name: Create Release
on:
  repository_dispatch:
    types: [trigger-build]
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - run: echo building