name: Test Semver
on: workflow_dispatch
jobs:
  create-release:
    name: Test Semver
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const branch = "${{ github.ref }}".split("/").pop()
            console.log(branch)
