name: Test Semver
on: workflow_dispatch
jobs:
  create-release:
    name: Test Semver
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - id: check-if-already-released
        uses: actions/github-script@v6
        with:
          script: |
            const tags = await github.paginate(
              github.rest.repos.listTags, 
              {owner: "CarnegieLearningWeb", repo: "UpGrade"}
            );
            console.log(tags)
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: "CarnegieLearningWeb",
              repo: "UpGrade"
            });
            const branch = await github.rest.repos.getBranch({
              owner: "CarnegieLearningWeb",
              repo: "UpGrade",
              branch: "main"
            });
            console.log(branch);
            const result = tags.find(element => element.name === latestRelease.data.tag_name).commit.sha === branch.data.commit.sha;
            console.log(result);
            return result;
      - run: echo "I ran"
        if: steps.check-if-already-released.outputs.result
