name: Test Semver
on: workflow_dispatch
jobs:
  create-release:
    name: Test Semver
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - id: check-if-already-released
        uses: actions/github-script@v6
        with:
          script: |
            const tags = await github.paginate(
              github.rest.repos.listTags, 
              {owner: "${{ github.repository_owner }}", repo: "UpGrade"}
            );
            console.log(tags)
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: "CarnegieLearningWeb",
              repo: "UpGrade"
            });
            const tag = tags.find(element => element.name === latestRelease.data.tag_name)
            console.log(tag)
            return tag
