name: Test
on: workflow_dispatch
jobs:
  create-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: CarnegieLearningWeb/UpGrade
          tag: "1.0.85"
          fileName: "*"