name: Create Release
on:
  repository_dispatch:
    types: [trigger-frontend-build]
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.ref }}