name: Test Semver
on: workflow_dispatch
jobs:
  create-release:
    name: Test Semver
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - id: check-if-already-released
        uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: "${{ github.repository_owner }}",
              repo: "UpGrade"
            });
            const latestReleaseTag = await github.rest.git.getTag({
              owner: "${{ github.repository_owner }}",
              repo: "UpGrade",
              tag_sha: latestRelease.data.tag_name
            });
            console.log(latestReleaseTag)
