# comment here
name: Test
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: phips28/gh-action-bump-version@v8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' ${{github.event.before}}..HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: frabert/replace-string-action@v1.2
        id: replaced-changelog
        with:
          pattern: '\n'
          string: ${{ env.CHANGELOG }}
          replace-with: '\\n'
      - uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_TOKEN }}
          channel: devops-test-channel
          payload: >-
            {
              "text": "*Test Action Successful Build*\n${{ steps.replaced-changelog.outputs.replaced }}",
              "color": "bad"
            }
