name: Release
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: kaangokdemir/github-version-bumper@0.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - uses: Bullrich/generate-release-changelog@2.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.package-version.outputs.current-version}}
          name: Test Action Release ${{ steps.package-version.outputs.current-version}}
          body: ${{ steps.changelog.outputs.changelog }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}

