name: Release
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: kaangokdemir/github-version-bumper@0.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: scottbrenner/generate-changelog-action@1.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - run: npm install --production
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r test-action-artifact-${{ steps.package-version.outputs.current-version}}.zip node_modules package.json dummy1.txt dummy3.stuff
      - uses: ncipollo/release-action@v1
        with:
          artifact: test-action-artifact-${{ steps.package-version.outputs.current-version}}.zip
          tag: ${{ steps.package-version.outputs.current-version}}
          name: Test Action Release ${{ steps.package-version.outputs.current-version}}
          body: ${{ steps.Changelog.outputs.changelog }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shallwefootball/s3-upload-action@v1.1.2
        with:
          source_dir: test-action-artifact-${{ steps.package-version.outputs.current-version}}.zip
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
