# comment here
name: Test
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: phips28/gh-action-bump-version@v8.0.18
        id: main-version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'main-major-version-bump'
          minor-wording: 'main-minor-version-bump'
          commit-message: 'CI: bump version for main project to {{version}}'
      - uses: phips28/gh-action-bump-version@v8.0.18
        id: frontend-version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: frontend
        with:
          major-wording: 'frontend-major-version-bump'
          minor-wording: 'frontend-minor-version-bump'
          commit-message: 'CI: bump version for frontend to {{version}}'
      - name: Trigger build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-main-build
          client-payload: '{"tag": "${{ steps.main-version-bump.outputs.newTag }}"}'
      - name: Trigger build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-frontend-build
          client-payload: '{"tag": "${{ steps.frontend-version-bump.outputs.newTag }}"}'
