name: Test
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - run: |
          echo ::set-env name=CHANGELOG::$(git log --reverse --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%ae)' ${{github.event.before}}..${{github.event.after}})
      - uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: devops-test-channel
          message: |
            *UpGrade Backend ${{ steps.package-version.outputs.current-version }} has been deployed to qa-cli.net*
            {{ env.CHANGELOG }}
