name: Test
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/slack-messaging-action@v1.0.0
        id: slack-message
        with:
          bot_token: ${{ secrets.SLACK_TOKEN }}
          channel: devops-test-channel
          payload: >-
            {
              "text": "Test message"
            }
      - uses: wearerequired/slack-messaging-action@v1.0.0
        with:
          bot_token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ steps.slack-message.outputs.message_id }}
          payload: >-
            {
              "text": "This should be a thread"
            }
